# Thème kanagawa-wave pour d2. À préfixer au diagramme.
vars: {
  d2-config: {
    theme-id: 200
    theme-overrides: {
      N1: "#DCD7BA"
      N2: "#C8C093"
      N3: "#727169"
      N4: "#54546D"
      N5: "#363646"
      N6: "#1F1F28"
      N7: "#16161D"
      B1: "#7E9CD8"
      B2: "#2D4F67"
      B3: "#727169"
      B4: "#1F1F28"
      B5: "#2A2A37"
      B6: "#1F1F28"
      AA2: "#D27E99"
      AA4: "#363646"
      AA5: "#2A2A37"
      AB4: "#363646"
      AB5: "#2A2A37"
    }
  }
}
