include kanagawa_dragon.conf

# FONT
font_family Hack Nerd Font
bold_font auto
italic_font auto
bold_italic_font auto
font_size 11

# BEHAVIOUR
shell                   /usr/bin/fish

scrollback_lines        10000
confirm_os_window_close 0
shell_integration       enabled

# souris désactivée
mouse_hide_wait         0
click_interval          -1.0
focus_follows_mouse     no

notify_on_cmd_finish unfocused 10.0

clear_all_shortcuts yes

# CLIPBOARD
map ctrl+y copy_and_clear_or_interrupt
map ctrl+p paste_from_clipboard

# SCROLLBACK
scrollback_pager nvim --cmd 'set eventignore=FileType' +'nnoremap q ZQ' +'call nvim_open_term(0, {})' +'set nomodified nolist' +'$' -
map ctrl+x show_scrollback
map alt+l scroll_to_prompt 1
map alt+p scroll_to_prompt -1

# KITTENS
map alt+u kitten hints --type url
map alt+c kitten hints --type path --program @
map alt+h kitten hints --type hash --program @
