[mgr]
prepend_keymap = [
  { on = "h", run = "leave", desc = "Back to the parent directory" },
  { on = "t", run = "arrow next", desc = "Next line" },
  { on = "n", run = "arrow prev", desc = "Previous line" },
  { on = "s", run = "enter", desc = "Enter the child directory" },
  { on = "T", run = "plugin parent-arrow 1", desc = "Next parent" },
  { on = "N", run = "plugin parent-arrow -1", desc = "Previous parent" },
  { on = "m", run = "plugin bookmarks save", desc = "Save current position as a bookmark" },
  { on = "'", run = "plugin bookmarks jump", desc = "Jump to a bookmark" },
  { on = [
    "b",
    "d",
  ], run = "plugin bookmarks delete", desc = "Delete a bookmark" },
  { on = [
    "b",
    "D",
  ], run = "plugin bookmarks delete_all", desc = "Delete all bookmarks" },
  { on = "x", run = 'shell "$SHELL" --block', desc = "Open $SHELL here" },
  { on = "y", run = [
    "copy path",
    "yank",
  ], desc = "Copy paths" },
]
